# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-11 06:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[(b'punjab', 'Punjab'), (b'sindh', 'Sindh'), (b'kpk', 'Khyber Pakhtunkhwa'), (b'balochistan', 'Balochistan')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_extension', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
