# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verify_student', '0005_remove_deprecated_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='softwaresecurephotoverification',
            options={},
        ),
    ]
