# Generated by Django 2.2.15 on 2020-10-08 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearesultCreditProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_code', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCreditsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_id', models.CharField(max_length=255)),
                ('credit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearesult_features.ClearesultCreditProvider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'credit_type')},
            },
        ),
        migrations.CreateModel(
            name='ClearesultCourseCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_value', models.IntegerField(default=0)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('credit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearesult_features.ClearesultCreditProvider')),
            ],
            options={
                'unique_together': {('credit_type', 'course_id')},
            },
        ),
    ]
