# Generated by Django 2.2.15 on 2020-10-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearesult_features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreditsprofile',
            name='earned_course_credits',
            field=models.ManyToManyField(blank=True, related_name='earned_credits', to='clearesult_features.ClearesultCourseCredit'),
        ),
        migrations.AlterField(
            model_name='clearesultcoursecredit',
            name='credit_value',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
