# Generated by Django 2.2.15 on 2020-10-13 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearesult_features', '0002_auto_20201009_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearesultcoursecredit',
            name='credit_value',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
