# Generated by Django 2.2.15 on 2020-10-13 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import openedx.features.clearesult_features.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clearesult_features', '0003_auto_20201013_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearesultUsersImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_accounts_file', models.FileField(null=True, upload_to='clearesult_features/user_accounts_file', validators=[openedx.features.clearesult_features.validators.validate_csv_extension])),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClearesultUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=25)),
                ('company', models.CharField(blank=True, max_length=25)),
                ('state_or_province', models.CharField(blank=True, max_length=25)),
                ('postal_code', models.CharField(blank=True, max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clearesult_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clearesult user profiles',
            },
        ),
    ]
