# Generated by Django 2.2.15 on 2020-10-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clearesult_features', '0004_clearesultuserprofile_clearesultusersimport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClearesultUsersImport',
        ),
    ]
