# Generated by Django 2.2.15 on 2020-10-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearesult_features', '0005_delete_clearesultusersimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearesultuserprofile',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clearesultuserprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clearesultuserprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clearesultuserprofile',
            name='state_or_province',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
