# Generated by Django 2.2.15 on 2020-10-23 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clearesult_features', '0006_auto_20201016_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearesultSiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('security_code', models.CharField(max_length=20, verbose_name='Site security code')),
                ('security_code_required', models.BooleanField(default=True)),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clearesult_configuration', to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'Clearesult Site Configurations',
            },
        ),
    ]
