# Generated by Django 2.2.15 on 2020-10-26 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clearesult_features', '0008_clearesultusersiteprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearesultsiteconfiguration',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearesult_configuration', to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='clearesultusersiteprofile',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='clearesultusersiteprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearesult_site_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
