# Generated by Django 2.2.15 on 2020-12-07 08:53

import collections
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clearesult_features', '0010_auto_20201027_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearesultuserprofile',
            name='extensions',
            field=jsonfield.fields.JSONField(blank=True, default=dict, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
        migrations.AlterField(
            model_name='usercreditsprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credit_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
