# Generated by Django 2.2.15 on 2020-12-07 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clearesult_features', '0011_auto_20201207_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearesulCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255, unique=True)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'Clearesult Courses',
            },
        ),
        migrations.CreateModel(
            name='ClearesulCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('clearesult_courses', models.ManyToManyField(blank=True, related_name='courses', to='clearesult_features.ClearesulCourse')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'unique_together': {('name', 'site')},
                'verbose_name_plural': 'Clearesult Catalogs',
            },
        ),
        migrations.CreateModel(
            name='ClearesulGroupLinkage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('assigned_catalogs', models.ManyToManyField(blank=True, related_name='catalogs', to='clearesult_features.ClearesulCatalog')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'site')},
                'verbose_name_plural': 'Clearesult User Groups',
            },
        ),
    ]
