# Generated by Django 2.2.15 on 2020-12-16 00:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('clearesult_features', '0012_clearesulcatalog_clearesulcourse_clearesulgrouplinkage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClearesulCatalog',
            new_name='ClearesultCatalog',
        ),
        migrations.RenameModel(
            old_name='ClearesulCourse',
            new_name='ClearesultCourse',
        ),
        migrations.RenameModel(
            old_name='ClearesulGroupLinkage',
            new_name='ClearesultGroupLinkage',
        ),
    ]
