# Generated by Django 2.2.15 on 2021-01-05 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clearesult_features', '0014_clearesultlocaladmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearesultGroupLinkedCatalogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory', models.BooleanField(default=False)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearesult_features.ClearesultCatalog')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearesult_features.ClearesultGroupLinkage')),
            ],
            options={
                'verbose_name_plural': 'Clearesult Group Catalogs',
            },
        ),
        migrations.AddField(
            model_name='clearesultgrouplinkage',
            name='catalogs',
            field=models.ManyToManyField(blank=True, related_name='linked_catalogs', through='clearesult_features.ClearesultGroupLinkedCatalogs', to='clearesult_features.ClearesultCatalog'),
        ),
    ]
