# Generated by Django 2.2.15 on 2021-01-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clearesult_features', '0015_auto_20210105_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearesultgrouplinkage',
            name='assigned_catalogs',
        ),
    ]
