# Generated by Django 2.2.15 on 2021-01-07 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clearesult_features', '0016_remove_clearesultgrouplinkage_assigned_catalogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearesultgrouplinkedcatalogs',
            name='mandatory',
        ),
        migrations.AddField(
            model_name='clearesultgrouplinkedcatalogs',
            name='mandatory_courses',
            field=models.ManyToManyField(blank=True, related_name='mandatory_courses', to='clearesult_features.ClearesultCourse'),
        ),
        migrations.AlterField(
            model_name='clearesultcatalog',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='clearesultcourse',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
