# Generated by Django 2.2.15 on 2021-01-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clearesult_features', '0017_auto_20210107_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clearesultgrouplinkedcatalogs',
            options={'verbose_name_plural': 'Clearesult Group Catalogs Mandatory Courses'},
        ),
    ]
