# Generated by Django 2.2.15 on 2021-01-20 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('clearesult_features', '0020_auto_20210118_1214'), ('clearesult_features', '0021_auto_20210118_1335'), ('clearesult_features', '0022_auto_20210118_1343'), ('clearesult_features', '0023_auto_20210120_1226')]

    dependencies = [
        ('clearesult_features', '0019_clearesultcoursecompletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearesultcoursecompletion',
            name='completion_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='clearesultcoursecompletion',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearesultcoursecompletion',
            name='pass_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='clearesultcoursecompletion',
            unique_together={('course_id', 'user')},
        ),
        migrations.AlterField(
            model_name='clearesultcoursecompletion',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearesultcoursecompletion',
            name='pass_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
