# Generated by Django 2.2.15 on 2021-01-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clearesult_features', '0019_clearesultusersession'),
        ('clearesult_features', '0020_auto_20210118_1214_squashed_0023_auto_20210120_1226'),
    ]

    operations = [
    ]
