# Generated by Django 2.2.15 on 2021-02-01 10:03

from django.db import migrations, models
import django.db.models.deletion
import openedx.features.clearesult_features.models


class Migration(migrations.Migration):

    dependencies = [
        ('clearesult_features', '0021_merge_20210121_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearesultsiteconfiguration',
            name='default_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clearesult_features.ClearesultGroupLinkage'),
        ),
        migrations.AlterField(
            model_name='clearesultsiteconfiguration',
            name='security_code',
            field=openedx.features.clearesult_features.models.EncryptedTextField(blank=True, max_length=20, null=True, verbose_name='Site security code'),
        ),
    ]
