# Generated by Django 2.2.15 on 2021-03-30 10:48

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('clearesult_features', '0022_auto_20210201_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearesultsiteconfiguration',
            name='mandatory_courses_alotted_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearesultsiteconfiguration',
            name='mandatory_courses_notification_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClearesultCourseConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('mandatory_courses_alotted_time', models.IntegerField(blank=True, null=True)),
                ('mandatory_courses_notification_period', models.IntegerField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'unique_together': {('course_id', 'site')},
            },
        ),
    ]
