# Generated by Django 2.2.15 on 2021-04-05 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_userprofile_state'),
        ('clearesult_features', '0023_auto_20210330_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearesultCourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField()),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.CourseEnrollment')),
            ],
        ),
    ]
