# Generated by Django 2.2.15 on 2021-04-12 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearesult_features', '0024_clearesultcourseenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearesultcoursecredit',
            name='credit_value',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
