# Generated by Django 2.2.15 on 2021-05-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clearesult_features', '0025_auto_20210412_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clearesultuserprofile',
            old_name='job_title',
            new_name='site_identifiers',
        ),
    ]
