# Generated by Django 2.2.15 on 2021-06-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearesult_features', '0026_auto_20210520_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearesultcourse',
            name='is_event',
            field=models.BooleanField(default=False, verbose_name='Is Event'),
        ),
    ]
