# Generated by Django 2.2.15 on 2021-06-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearesult_features', '0027_clearesultcourse_is_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clearesultcourseconfig',
            old_name='mandatory_courses_alotted_time',
            new_name='mandatory_courses_allotted_time',
        ),
        migrations.RemoveField(
            model_name='clearesultsiteconfiguration',
            name='mandatory_courses_alotted_time',
        ),
        migrations.AddField(
            model_name='clearesultsiteconfiguration',
            name='courses_notification_period',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='clearesultsiteconfiguration',
            name='events_notification_period',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='clearesultsiteconfiguration',
            name='mandatory_courses_allotted_time',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name='clearesultsiteconfiguration',
            name='mandatory_courses_notification_period',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
