# Generated by Django 2.2.15 on 2021-07-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearesult_features', '0028_auto_20210621_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearesultsiteconfiguration',
            name='participation_code_required',
            field=models.BooleanField(default=False),
        ),
    ]
