# Generated by Django 2.2.15 on 2021-07-23 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clearesult_features', '0029_clearesultsiteconfiguration_participation_code_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationGroupCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clearesult_features.ClearesultGroupLinkage')),
            ],
        ),
    ]
