# Generated by Django 2.2.15 on 2021-08-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearesult_features', '0030_participationgroupcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearesultCourseMetaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
