# Generated by Django 2.2.15 on 2021-08-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearesult_features', '0031_clearesultcoursemetatag'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearesultcourse',
            name='meta_tags',
            field=models.CharField(default='', max_length=255),
        ),
    ]
