# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-16 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': 'Course Category', 'verbose_name_plural': 'Course Categories'},
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='category',
            field=models.ManyToManyField(blank=True, to='course_category.Category'),
        ),
    ]

