# Generated by Django 3.2.20 on 2024-03-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecompletionemailhistory',
            name='is_completion_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
