# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-07 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edly', '0004_edlysuborganization_preview_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='edlyuserprofile',
            name='dummy_field',
            field=models.CharField(help_text=b'Field added for migration rollback testing.', max_length=255, null=True),
        ),
    ]
