# -*- coding: utf-8 -*-
# pylint: skip-file
# Generated by Django 2.2.16 on 2021-08-10 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_squashed_0007_historicalorganization'),
        ('edly', '0006_edlyuserprofile_course_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edlyorganization',
            name='slug',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(
                '^[0-9a-z-]*$', 'Only small case alphanumeric and hyphen characters are allowed.')]),
        ),
        migrations.AddField(
            model_name='edlysuborganization',
            name='edx_organizations',
            field=models.ManyToManyField(to='organizations.Organization'),
        ),
        migrations.AlterField(
            model_name='edlysuborganization',
            name='slug',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(
                '^[0-9a-z-]*$', 'Only small case alphanumeric and hyphen characters are allowed.')]),
        ),
        migrations.AlterUniqueTogether(
            name='edlysuborganization',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='edlysuborganization',
            name='edx_organization',
        ),
    ]
