# pylint: skip-file
# Generated by Django 2.2.16 on 2022-01-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edly', '0008_edlyuserprofile_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='edlysuborganization',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
