# Generated by Django 2.2.24 on 2024-06-25 18:49

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('edly', '0013_edlymultisiteaccess_has_unsubscribed_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatlyWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sync_date', models.DateTimeField(blank=True, null=True)),
                ('is_enable', models.BooleanField(default=False)),
                ('course_key', models.CharField(max_length=255, unique=True)),
                ('bot_key', models.CharField(max_length=255, null=True, unique=True)),
                ('bot_id', models.IntegerField(blank=True, null=True)),
                ('allowed_directories', models.IntegerField(blank=True, null=True)),
                ('unable_to_answer_response', models.CharField(default='nothing', max_length=15, null=True)),
                ('temperature', models.DecimalField(decimal_places=1, default='1.0', max_digits=2)),
                ('prompt', models.TextField(default="Use the following pieces of context to answer the question at the end.\nIf you don't know the answer, just say that you don't know, don't try to make up an answer.\n{context}\nQuestion: {question}\nHelpful Answer:")),
                ('advanced_mode', models.BooleanField(default=False)),
                ('ai_output_focus', models.CharField(blank=True, max_length=255, null=True)),
                ('last_sync_json', jsonfield.fields.JSONField(null=True)),
                ('sync_date', models.DateTimeField(blank=True, null=True)),
                ('sync_json', jsonfield.fields.JSONField(null=True)),
                ('sync_status', models.IntegerField(blank=True, default=1, null=True)),
                ('sync_error', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
