# Generated by Django 2.2.24 on 2024-09-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edly', '0014_chatlywidget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatlyWidget',
        ),
    ]
