# Generated by Django 2.2.24 on 2024-11-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edly', '0015_delete_chatlywidget'),
    ]

    operations = [
        migrations.AddField(
            model_name='edlyuserprofile',
            name='is_social_user',
            field=models.BooleanField(default=False, help_text='Record that the user is linked with social oauth through free trial.', verbose_name='social user'),
        ),
    ]
