# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-01 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_add_user_subscription_history_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
