# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-02 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_usersubscription_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionhistory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
