# Generated by Django 2.2.17 on 2021-03-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_auto_20201021_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='npi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
