# Generated by Django 3.2.20 on 2023-09-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0044_courseenrollmentcelebration_celebrate_weekly_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employement_status',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='english_language_level',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signup_form_options',
            field=models.JSONField(default={'employement_status': ['Public industry', 'Private industry', 'Job seeker', 'Student'], 'english_language_level': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 'region': ['Riyadh', 'Eastern', 'Asir', 'Jazan', 'Medina', 'Al-Qassim', 'Tabuk', "Ha'il", 'Najran', 'Al-Jawf', 'Al-Bahah', 'Northern Borders'], 'type_of_degree': ['Middle School', 'High School', 'Diploma', 'Bachelor', 'Master', 'Ph.D.'], 'work_experience_level': ['Junior level (0-2) years', 'Middle level (3-4) years', 'Senior level (5-10) years', 'Expert (+ 10 years)']}),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='type_of_degree',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_experience_level',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
