# Generated by Django 3.2.21 on 2023-10-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0046_alter_userprofile_english_language_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='terms_and_conditions',
            field=models.BooleanField(default=True),
        ),
    ]
