# Generated by Django 3.2.20 on 2024-06-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0047_userprofile_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='arabic_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
